---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-telegram-bot
  namespace: monitoring
  labels:
    app: prometheus-telegram-bot
spec:
  ports:
  - port: 8081
    protocol: TCP
    name: http
  selector:
    app: prometheus-telegram-bot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-telegram-bot
  namespace: monitoring
  labels:
    app: prometheus-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-telegram-bot
  template:
    metadata:
      labels:
        app: prometheus-telegram-bot
    spec:
      volumes:
      - name: config
        configMap:
          name: prometheus-telegram-bot-config
      containers:
      - name: prometheus-bot
        image: solyard/weasel:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "50M"
      volumeMounts:
        - mountPath: config.yaml
          name: config
          subPath: config/config.yaml
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-telegram-bot-config
  namespace: monitoring
data:
  config.yaml: |
    botToken: "<TOKEN>"
